# Generated by Django 2.2 on 2020-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotegroup',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
