# Generated by Django 2.2 on 2019-12-23 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.FileField(upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SquadRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'SCO'), (1, 'CO'), (2, 'XO'), (3, 'HCO'), (4, 'SL'), (5, 'NCO'), (6, 'Grunt'), (7, 'Reserve')], default=7)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Squad')),
            ],
            options={
                'ordering': ['squad', 'role', 'player'],
                'unique_together': {('squad', 'player')},
            },
        ),
        migrations.AddField(
            model_name='squad',
            name='players',
            field=models.ManyToManyField(through='roster.SquadRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Team'),
        ),
    ]
