# Generated by Django 2.2 on 2019-02-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SquadRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Commander'), (1, 'Officer'), (2, 'Squad Leader'), (3, 'NCO'), (4, 'Grunt'), (5, 'Reserve')], default=5)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Squad')),
            ],
            options={
                'ordering': ['squad', 'role', 'player'],
                'unique_together': {('squad', 'player')},
            },
        ),
        migrations.AddField(
            model_name='squad',
            name='players',
            field=models.ManyToManyField(through='roster.SquadRole', to='roster.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='squads',
            field=models.ManyToManyField(through='roster.SquadRole', to='roster.Squad'),
        ),
    ]
